### ISSUE TITLE
When creating a "Frame" when using a laptop with a function key, "F6" input isn't registerd

### ISSUE THREAD

**Issue by WillowTough** [gregzaal/node_wrangler#3]
On a keyboard or laptop and using node wrangler you can create a frame as you should be able to, but when attempting to change the colour and the title of the frame `F6` doesn't register as an input.

**Steps to reproduce:**

1. Open node editor on a computer using a function key
2. Create a frame using the `shift-p` hotkey
3. Press `Function-F6` to change the colour and the title of the frame
3-a. Repeat steps 1-2 and instead just press `F6` 

**Expected result:**
Ability to change the colour and title of the frame.

**Actual result:**
Nothing happens

**Suggestion to fix:**
Add the `F6` key to the shortcuts menu. This would allow it to be bound to another key making the problem of the function key not present.

**Comment by gregzaal** [comment]
This is not the active repo for NW, I no longer maintain it. Please report the bug to the official blender bug tracker using this link:

![2022-01-21_12-13-32_blender](https://user-images.githubusercontent.com/5604661/150509254-6a108779-ed9a-4b62-ab13-5c3896e845c5.png)
